name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: ${{ secrets.SECRET_KEY }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      RDS_NAME: ${{ secrets.RDS_NAME }}
      RDS_PWD: ${{ secrets.RDS_PWD }}
      RDS_HOST: ${{ secrets.RDS_HOST }}
      RDS_USER: ${{ secrets.RDS_USER }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Run test and coverage
      run: |
        coverage run --source=./ -m pytest
    
    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      with:
        coverageCommand: coverage xml
        coverageLocations: ${{github.workspace}}/coverage.xml:coverage.py
      env:
        CC_TEST_REPORTER_ID: 0d923aab5913acb3cf22f3b438a407331f8a6af376397b754b624e1e41620beb
